"""empty message

Revision ID: ba9ab2f6bbfc
Revises: 13c7bf12bcec
Create Date: 2020-03-09 14:30:31.432990

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ba9ab2f6bbfc'
down_revision = '13c7bf12bcec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sensors', sa.Column('lat', sa.Float(), nullable=True))
    op.add_column('sensors', sa.Column('lon', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sensors', 'lon')
    op.drop_column('sensors', 'lat')
    # ### end Alembic commands ###
