"""Temperature and Humidity tables

Revision ID: e0c5315cd358
Revises: 
Create Date: 2020-03-02 15:14:10.551993

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e0c5315cd358'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('humidity',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('humidity', sa.Float(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_humidity_timestamp'), 'humidity', ['timestamp'], unique=False)
    op.create_table('temperature',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('temperature', sa.Float(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_temperature_timestamp'), 'temperature', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_temperature_timestamp'), table_name='temperature')
    op.drop_table('temperature')
    op.drop_index(op.f('ix_humidity_timestamp'), table_name='humidity')
    op.drop_table('humidity')
    # ### end Alembic commands ###
